import React, {useEffect,useState} from 'react';
import Swal from 'sweetalert2';
import {fetchWithAuth} from '../../../../api';
export default function GSOFleetPanel({assets}) {
  const [data,setData]=useState({vehicles:[],drivers:[],requests:[]});
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const [selected,setSelected]=useState(null);const [options,setOptions]=useState(null);
  const [travelStart,setTravelStart]=useState('');const [travelEnd,setTravelEnd]=useState('');
  const [vehicleId,setVehicleId]=useState('');const [driverId,setDriverId]=useState('');
  async function api(path, method='GET', body) {
    const res=await fetchWithAuth(`/api/resources/${path}`,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
    const value=await res.json();if(!res.ok)throw new Error(value.error || 'Request failed.');return value;
  }
  async function refresh(){try{setData(await api('fleet'));setError('');}catch(e){setError(e.message);}}
  useEffect(()=>{refresh();},[]);
  async function action(fn){setBusy(true);try{await fn();await refresh();}catch(e){await Swal.fire({icon:'error',title:'Could not save',text:e.message});}finally{setBusy(false);}}
  async function choose(request){setTravelStart(request.start?.slice(0,5)||'');setTravelEnd(request.end?.slice(0,5)||'');setSelected(request);setOptions(null);setVehicleId('');setDriverId('');try{setOptions(await api(`assignments/${request.booking_id}/options`));}catch(e){setOptions({vehicles:[],drivers:[],reason:e.message});}}
  const input='border border-gray-300 rounded-lg p-2 text-sm w-full';
  return <section className="bg-white border rounded-2xl p-6 space-y-5">
    <header><h3 className="text-lg font-bold">Vehicle and driver assignments</h3><p className="text-sm text-gray-500 mt-1">Register each physical vehicle and driver. Assign a pair before completing the document checklist. Pending assignments do not reserve a time.</p></header>
    {error && <p role="alert" className="text-red-700">{error}</p>}
    <div className="grid md:grid-cols-2 gap-5">{['vehicles','drivers'].map(kind=><form key={kind} className="rounded-xl bg-gray-50 border p-4 space-y-3" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const body=Object.fromEntries(new FormData(form));action(async()=>{await api(`fleet/${kind}`,'POST',body);form.reset();});}}>
      <h4 className="font-semibold">Register {kind==='vehicles'?'vehicle':'driver'}</h4>
      {kind==='vehicles' && <select required name="assetId" aria-label="Vehicle asset" className={input}><option value="">Select vehicle asset</option>{assets.filter(a=>a.ast_id===4).map(a=><option key={a.asd_id} value={a.asd_id}>{a.asset_name}</option>)}</select>}
      <input required name="name" aria-label={kind==='vehicles'?'Vehicle name':'Driver name'} placeholder={kind==='vehicles'?'Vehicle name':'Driver name'} className={input}/>
      <input required name="number" aria-label={kind==='vehicles'?'Plate number':'License number'} placeholder={kind==='vehicles'?'Plate number':'License number'} className={input}/>
      <button disabled={busy} className="bg-red-800 text-white px-4 py-2 rounded-lg text-sm">Register</button>
      <div className="space-y-2">{data[kind].map(item=><div key={item.vehicle_id||item.driver_id} className="flex items-center justify-between gap-2 text-xs"><span>{item.vehicle_name||item.full_name} · {item.plate_number||item.license_number}</span><button disabled={busy} type="button" className="border rounded px-2 py-1" onClick={()=>action(()=>api(`fleet/${kind}/${item.vehicle_id||item.driver_id}/active`,'PUT',{active:!item.is_active}))}>{item.is_active?'Mark unavailable':'Mark available'}</button></div>)}</div>
    </form>)}</div>
    <div className="max-h-80 overflow-y-auto space-y-2">{data.requests.map(request=><div key={request.booking_id} className="border rounded-xl p-3 flex flex-wrap items-center justify-between gap-3 text-sm"><div><p className="font-semibold">{request.date} · {request.start?.slice(0,5)} – {request.end?.slice(0,5)}</p><p>{request.full_name} · {request.status==='Confirmed'?'Confirmed':'Pending'}</p><p className="text-xs text-gray-500">{data.vehicles.find(v=>v.vehicle_id===request.assigned_vehicle_id)?.vehicle_name||'Vehicle to be assigned'} · {data.drivers.find(d=>d.driver_id===request.assigned_driver_id)?.full_name||'Driver to be assigned'}</p></div><button type="button" className="border rounded-lg p-2" onClick={()=>choose(request)}>Assign vehicle / driver</button></div>)}</div>
    {selected && <div role="dialog" aria-modal="true" aria-label="Assign vehicle and driver" className="fixed inset-0 z-[130] bg-black/40 flex items-center justify-center p-4"><form className="bg-white p-6 rounded-2xl w-full max-w-lg space-y-4" onSubmit={e=>{e.preventDefault();action(async()=>{const result=await api(`assignments/${selected.booking_id}`,'PUT',{vehicleId,driverId,start:travelStart,end:travelEnd});setSelected(null);await Swal.fire({icon:'success',title:'Assignment saved',text:result.message});});}}><h4 className="font-bold">Assign for {selected.date} · {selected.start?.slice(0,5)} – {selected.end?.slice(0,5)}</h4><div className="grid grid-cols-2 gap-3"><label className="text-sm">Departure<input type="time" required value={travelStart} onChange={e=>{setTravelStart(e.target.value);setVehicleId('');setDriverId('')}} className={input}/></label><label className="text-sm">Arrival<input type="time" required value={travelEnd} onChange={e=>{setTravelEnd(e.target.value);setVehicleId('');setDriverId('')}} className={input}/></label></div><button type="button" onClick={()=>action(async()=>{setOptions(await api(`assignments/${selected.booking_id}/options?${new URLSearchParams({start:travelStart,end:travelEnd})}`));})} className="text-sm underline">Refresh available options for these times</button>{!options?<p>Checking available vehicles and drivers…</p>:<><p className="text-sm text-gray-500">{options.reason}</p><label className="block text-sm">Vehicle<select required value={vehicleId} onChange={e=>setVehicleId(e.target.value)} className={input}><option value="">Select vehicle</option>{options.vehicles.map(v=><option key={v.vehicle_id} value={v.vehicle_id}>{v.vehicle_name} · {v.plate_number}</option>)}</select></label><label className="block text-sm">Driver<select required value={driverId} onChange={e=>setDriverId(e.target.value)} className={input}><option value="">Select driver</option>{options.drivers.map(d=><option key={d.driver_id} value={d.driver_id}>{d.full_name}</option>)}</select></label></>}<div className="flex justify-end gap-3"><button type="button" disabled={busy} onClick={()=>setSelected(null)}>Cancel</button><button disabled={busy||!vehicleId||!driverId} className="bg-red-800 text-white rounded-lg px-4 py-2 disabled:opacity-40">Save assignment</button></div></form></div>}
  </section>;
}
