import React,{useState} from 'react';
import {ChevronLeft,ChevronRight,Plus,X,CalendarDays} from 'lucide-react';
import {resourceApi,confirmResourceAction,resourceSuccess,resourceError} from '../resourceActions';
import {dateKey,blockOnDay} from '../../../../utils/resourceSchedule';
const control='border border-gray-300 rounded-lg px-3 py-2 text-sm';
export default function ResourceAdminCalendar({requests,blocks,assets,fleet,onRefresh,onOpenRequest}) {
  const [month,setMonth]=useState(new Date());
  const [resource,setResource]=useState('All');const [status,setStatus]=useState('All');
  const [day,setDay]=useState(null);const [block,setBlock]=useState(null);const [busy,setBusy]=useState(false);
  const year=month.getFullYear(), index=month.getMonth();
  const today=new Date().toLocaleDateString('en-CA');
  const typeMap={Vehicle:4,Room:1,Gymnasium:2};
  const filteredRequests=requests.filter(r=>(resource==='All'||r.booking_type===resource)&&(status==='All'||r.status===status));
  const filteredBlocks=blocks.filter(b=>(resource==='All'||b.ast_id===typeMap[resource])&&(status==='All'||status==='Blocked'));
  const entries=date=>[...filteredRequests.filter(r=>dateKey(r.reservation_date)===date).map(r=>({kind:'request',record:r,label:r.status==='Confirmed'?'Confirmed':'Pending'})),...filteredBlocks.filter(b=>blockOnDay(b,date)).map(b=>({kind:'block',record:b,label:'Blocked'}))];
  const colors={Confirmed:'bg-emerald-50 text-emerald-800 border-emerald-200',Pending:'bg-amber-50 text-amber-800 border-amber-200',Blocked:'bg-red-50 text-red-800 border-red-200'};
  const eventColors={Confirmed:'bg-emerald-100 text-emerald-950 border-emerald-600',Pending:'bg-amber-100 text-amber-950 border-amber-500',Blocked:'bg-red-100 text-red-950 border-red-600'};
  function openBlock(date) {setBlock({date,target:'',wholeDay:true,start:'08:00',end:'17:00',reason:''});}
  async function saveBlock(e) {
    e.preventDefault();if(busy)return;setBusy(true);
    try {
      if(!await confirmResourceAction('Block this period?',`${block.date} · ${block.wholeDay?'Whole day':`${block.start}–${block.end}`} · ${block.reason}`))return;
      const [kind,id]=block.target.split(':');
      const vehicle=kind==='v'?fleet.vehicles.find(v=>v.vehicle_id===Number(id)):null;
      const result=await resourceApi('schedule-blocks','POST',{...block,assetId:vehicle?vehicle.asd_id:Number(id),vehicleId:vehicle?.vehicle_id});
      setBlock(null);await onRefresh();await resourceSuccess(result.message);
    } catch(e){await resourceError(e);}finally{setBusy(false);}
  }
  async function removeBlock(record) {
    if(busy)return;setBusy(true);
    try {if(!await confirmResourceAction('Remove this block?',record.reason))return;const result=await resourceApi(`schedule-blocks/${record.block_id}`,'DELETE');await onRefresh();await resourceSuccess(result.message);}
    catch(e){await resourceError(e);}finally{setBusy(false);}
  }
  return <section className="bg-white border border-gray-200 border-t-4 border-t-[#D32F2F] rounded-2xl shadow-sm p-6 md:p-8 space-y-5">
    <header className="flex flex-wrap justify-between gap-4 border-b border-gray-100 pb-5"><div className="flex items-center gap-3"><div className="p-2 rounded-lg bg-red-50 text-[#D32F2F]"><CalendarDays size={22}/></div><div><h3 className="text-lg font-bold text-gray-900">Requests and availability calendar</h3><p className="text-sm text-gray-500 mt-1">View requests, open their requirements, or block a resource.</p></div></div><button className="inline-flex items-center gap-2 bg-gray-900 hover:bg-black text-white rounded-lg px-4 py-2 text-xs font-bold uppercase tracking-wide shadow-sm" onClick={()=>openBlock(day||today)}><Plus size={16}/>Add block</button></header>
    <div className="flex flex-wrap justify-between gap-3"><div className="flex flex-wrap gap-2"><select aria-label="Calendar resource filter" className={control} value={resource} onChange={e=>setResource(e.target.value)}><option value="All">All resources</option><option value="Vehicle">Vehicles</option><option value="Room">Multimedia Room</option><option value="Gymnasium">Gymnasium</option></select><select aria-label="Calendar status filter" className={control} value={status} onChange={e=>setStatus(e.target.value)}><option value="All">All requests and blocks</option><option value="Reserved">Pending</option><option value="Confirmed">Confirmed</option><option value="Blocked">Blocked periods</option></select></div><div className="flex items-center gap-3"><button aria-label="Previous month" className={control} onClick={()=>setMonth(new Date(year,index-1,1))}><ChevronLeft size={16}/></button><strong className="text-sm">{month.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</strong><button aria-label="Next month" className={control} onClick={()=>setMonth(new Date(year,index+1,1))}><ChevronRight size={16}/></button></div></div>
    <div className="flex flex-wrap gap-3" aria-label="Calendar status legend">{Object.keys(eventColors).map(label=><span key={label} className={`border-l-4 rounded-md px-3 py-1.5 text-xs font-bold ${eventColors[label]}`}>{label}</span>)}</div>
    <div className="overflow-x-auto"><div className="min-w-[980px] grid grid-cols-7 gap-2.5">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><div key={d} className="text-center text-xs font-bold uppercase tracking-wide text-gray-600 bg-gray-50 rounded-lg py-3">{d}</div>)}{Array.from({length:new Date(year,index,1).getDay()},(_,i)=><div key={`empty-${i}`} className="bg-gray-50/60 rounded-xl border border-dashed border-gray-200"/>)}{Array.from({length:new Date(year,index+1,0).getDate()},(_,i)=>{
      const date=`${year}-${String(index+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;
      const items=entries(date);
      return <button key={date} aria-label={`View schedule for ${date}`} onClick={()=>setDay(date)} className={`min-h-[180px] flex flex-col text-left p-2.5 border rounded-xl hover:border-red-600 hover:shadow-md transition-shadow focus-visible:ring-2 focus-visible:ring-red-500 ${date===today?'border-red-600 bg-red-50/30 ring-1 ring-red-100':'border-gray-200 bg-white'}`}>
        <span className={`w-8 h-8 inline-flex items-center justify-center rounded-full text-sm font-bold ${date===today?'bg-red-600 text-white':'text-gray-800'}`}>{i+1}</span>
        <div className="space-y-2 mt-2 w-full">{items.slice(0,2).map(item=><div key={`${item.kind}-${item.record.booking_id||item.record.block_id}`} className={`rounded-lg border-l-4 px-2.5 py-2.5 shadow-sm ${eventColors[item.label]}`}>
          <p className="text-xs font-extrabold">{item.label}</p>
          <p className="text-xs font-semibold mt-1">{item.kind==='request'?`${item.record.start_time?.slice(0,5)||'—'} – ${item.record.end_time?.slice(0,5)||'—'}`:item.record.whole_day?'Whole day':`${item.record.start_time.slice(11,16)} – ${item.record.end_time.slice(11,16)}`}</p>
          <p className="text-[13px] leading-snug font-semibold mt-1 break-words line-clamp-2" title={item.record.purpose||item.record.reason}>{item.record.purpose||item.record.vehicle_name||item.record.asset_name}</p>
        </div>)}{items.length>2&&<p className="text-xs font-bold text-gray-700 rounded-md bg-gray-100 px-2 py-1.5">+{items.length-2} more · View day</p>}</div>
      </button>;
    })}</div></div>
    {day&&!block&&<div className="fixed inset-0 z-[120] bg-black/40 backdrop-blur-sm flex items-center justify-center p-4"><section role="dialog" aria-modal="true" aria-label="Daily requests and blocks" className="w-full max-w-2xl max-h-[85vh] overflow-y-auto rounded-2xl bg-white p-6 space-y-4"><header className="flex justify-between"><div><h3 className="font-bold text-lg">{day}</h3><p className="text-sm text-gray-500">Showing the selected calendar filters.</p></div><button aria-label="Close daily schedule" onClick={()=>setDay(null)}><X size={20}/></button></header>{entries(day).map(item=><article key={`${item.kind}-${item.record.booking_id||item.record.block_id}`} className={`border rounded-xl p-4 ${colors[item.label]}`}>
      {item.kind==='request'?<button className="w-full text-left" onClick={()=>{setDay(null);onOpenRequest(item.record);}}><div className="flex justify-between gap-3 font-semibold text-sm"><span>Request #{item.record.booking_id} · {item.record.requestor}</span><span>{item.label}</span></div><p className="text-sm mt-2">{item.record.start_time?.slice(0,5)}–{item.record.end_time?.slice(0,5)} · {item.record.asset_name}</p><p className="text-sm">{item.record.purpose}</p><span className="text-xs underline mt-2 inline-block">Open Request Requirement →</span></button>:<><strong className="text-sm">Blocked · {item.record.vehicle_name||item.record.asset_name}{item.record.plate_number?` · ${item.record.plate_number}`:''}</strong><p className="text-xs mt-1">{item.record.whole_day?'Whole day':`${item.record.start_time.replace('T',' ')} – ${item.record.end_time.replace('T',' ')}`}</p><p className="text-sm mt-2">{item.record.reason}</p><button disabled={busy} className="text-xs underline mt-2" onClick={()=>removeBlock(item.record)}>Remove block</button></>}
    </article>)}{!entries(day).length&&<p className="text-sm text-gray-500 py-6">No matching requests or blocks for this day.</p>}<button className={`${control} bg-red-800 text-white`} onClick={()=>openBlock(day)}>Add block for this date</button></section></div>}
    {block&&<div className="fixed inset-0 z-[130] bg-black/40 backdrop-blur-sm flex items-center justify-center p-4"><form role="dialog" aria-modal="true" aria-label="Block a resource" onSubmit={saveBlock} className="rounded-2xl shadow-xl bg-white p-6 w-full max-w-lg space-y-5"><h3 className="text-lg font-bold">Block a resource</h3><fieldset disabled={busy} className="space-y-4"><label className="block text-sm">Resource<select required value={block.target} onChange={e=>setBlock({...block,target:e.target.value})} className={`${control} w-full mt-1`}><option value="">Choose a facility or individual vehicle</option>{assets.filter(a=>[1,2].includes(a.ast_id)).map(a=><option key={`a${a.asd_id}`} value={`a:${a.asd_id}`}>{a.asset_name}</option>)}{fleet.vehicles.map(v=><option key={`v${v.vehicle_id}`} value={`v:${v.vehicle_id}`}>{v.vehicle_name} · {v.plate_number}</option>)}</select></label><label className="block text-sm">Date<input required min={today} type="date" className={`${control} w-full mt-1`} value={block.date} onChange={e=>setBlock({...block,date:e.target.value})}/></label><label className="block text-sm">Block duration<select className={`${control} w-full mt-1`} value={String(block.wholeDay)} onChange={e=>setBlock({...block,wholeDay:e.target.value==='true'})}><option value="true">Whole day</option><option value="false">Specific time</option></select></label>{!block.wholeDay&&<div className="grid grid-cols-2 gap-3"><label className="text-sm">Start<input required type="time" value={block.start} onChange={e=>setBlock({...block,start:e.target.value})} className={`${control} w-full mt-1`}/></label><label className="text-sm">End<input required type="time" min={block.start} value={block.end} onChange={e=>setBlock({...block,end:e.target.value})} className={`${control} w-full mt-1`}/></label></div>}<label className="block text-sm">Reason<textarea required rows={3} className={`${control} w-full mt-1`} value={block.reason} onChange={e=>setBlock({...block,reason:e.target.value})}/></label></fieldset><footer className="flex justify-end gap-3 border-t pt-4"><button type="button" disabled={busy} onClick={()=>setBlock(null)} className={control}>Cancel</button><button disabled={busy} className={`${control} bg-red-800 text-white`}>Save block</button></footer></form></div>}
  </section>;
}
